# Ścieżki do folderów ze zdjęciami
train: ../piecesYOLO/train/images
val: ../piecesYOLO/valid/images

# Liczba klas
nc: 12

# Nazwy klas (w naszym przypadku tylko jedna)
names: ['white_pawn', 'white_rook', 'white_knight', 'white_bishop', 'white_queen', 'white_king', 'black_pawn', 'black_rook', 'black_knight', 'black_bishop', 'black_queen', 'black_king']